config/routes.rb
Rails.application.routes.draw do
  

  get 'landings/index'
  get 'spinoffs/index'
  get 'interactivecharts/index'
  get 'faq/show'

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :spinoffs
  resources :subscribe
  resources :interactivecharts
  resources :faq

  root 'spinoffs#index'

      

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/controllers/subscribe_controller.rb
class SubscribeController < ApplicationController
  before_filter :authenticate_user!



  def new
  end

  def update
    #get the credit card details submitted by the form
    token = params[:stripeToken]

    # Create a customer
    customer = Stripe::Customer.create(
      :card => token,
      :plan => 2499,
      :email => current_user.email
      )

      current_user.subscribed = true
      current_user.stripeid = customer.id
      current_user.save

      redirect_to spinoffs_index_path, :notice => "Your subscription was setup! You may now access the Spin-off subscription list!"
  end
end

app/helpers/subscribe_helper.rb
module SubscribeHelper
end

app/views/subscribe/new.html.erb
<div class="subscribe_wrap">
  <%= render partial: "elements/navbar" %>
  <%= bootstrap_flash %>
  <%= form_tag subscribe_path(1), :method => :put do %>    
    <div class="container full_screen">
    <article>
      <label class="amount">
        <span style="color: white; font-size: 2em; padding-bottom: 5px;">Amount: $24.99</span>
      </label>
    </article>

    <script src = "https://checkout.stripe.com/v2/checkout.js" class= "stripe-button"
        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
        data-description="A month's subscription"
        data-amount="2499"></script>
    <% end %>
    </div>
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <p>© Spinoff News Letter - Designed &amp; Developed by<br> <a href="http://www.ajeanwebdev.com/">Ajean Web Dev</a> &amp; <a href="https://github.com/palmbeachjeff">Palm Beach Jeff</a></p>
          </div>
        </div>
      </div>
    </footer>
</div>