config/routes.rb
Rails.application.routes.draw do
  

  get 'landings/index'
  get 'spinoffs/index'
  get 'interactivecharts/index'
  get 'faq/show'

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :spinoffs
  resources :subscribe
  resources :interactivecharts
  resources :faq

  root 'spinoffs#index'

      

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/spinoff.rb
class Spinoff < ActiveRecord::Base
end

app/controllers/spinoffs_controller.rb
class SpinoffsController < ApplicationController
  before_filter :authenticate_user!



  def index
    @spinoffs = Spinoff.paginate(per_page: 25, page: params[:page]) 
  end

  def show
    @spinoff = Spinoff.find(params[:id])
    @data_history_p = YahooFinance.historical_quotes(@spinoff.parent_ticker, { start_date: Time::now - (60*60*24*2770), end_date: Time::now })
    @data_history_s = YahooFinance.historical_quotes(@spinoff.spinoff_ticker, { start_date: Time::now - (60*60*24*2770), end_date: Time::now })
    @data = YahooFinance.quotes([@spinoff.parent_ticker, @spinoff.spinoff_ticker], [ :after_hours_change_real_time,
                                                                                     :annualized_gain, 
                                                                                     :ask,
                                                                                     :ask_real_time,
                                                                                     :ask_size,
                                                                                     :average_daily_volume,
                                                                                     :bid,
                                                                                     :bid_real_time,
                                                                                     :bid_size,
                                                                                     :book_value,
                                                                                     :change,
                                                                                     :change_and_percent_change,
                                                                                     :change_from_200_day_moving_average, 
                                                                                     :change_from_50_day_moving_average, 
                                                                                     :change_from_52_week_high, 
                                                                                     :change_From_52_week_low, 
                                                                                     :change_in_percent, 
                                                                                     :change_percent_realtime, 
                                                                                     :change_real_time,
                                                                                     :close, 
                                                                                     :comission,
                                                                                     :day_value_change, 
                                                                                     :day_value_change_realtime, 
                                                                                     :days_range,
                                                                                     :days_range_realtime, 
                                                                                     :dividend_pay_date, 
                                                                                     :dividend_per_share,
                                                                                     :dividend_yield,
                                                                                     :earnings_per_share,
                                                                                     :ebitda, 
                                                                                     :eps_estimate_current_year, 
                                                                                     :eps_estimate_next_quarter, 
                                                                                     :eps_estimate_next_year, 
                                                                                     :error_indicator, 
                                                                                     :ex_dividend_date,
                                                                                     :float_shares, 
                                                                                     :high, 
                                                                                     :high_52_weeks, 
                                                                                     :high_limit, 
                                                                                     :holdings_gain, 
                                                                                     :holdings_gain_percent, 
                                                                                     :holdings_gain_percent_realtime, 
                                                                                     :holdings_gain_realtime, 
                                                                                     :holdings_value, 
                                                                                     :holdings_value_realtime, 
                                                                                     :last_trade_date,
                                                                                     :last_trade_price,
                                                                                     :last_trade_realtime_withtime, 
                                                                                     :last_trade_size, 
                                                                                     :last_trade_time, 
                                                                                     :last_trade_with_time, 
                                                                                     :low, 
                                                                                     :low_52_weeks, 
                                                                                     :low_limit, 
                                                                                     :market_cap_realtime, 
                                                                                     :market_capitalization, 
                                                                                     :more_info, 
                                                                                     :moving_average_200_day, 
                                                                                     :moving_average_50_day, 
                                                                                     :name, 
                                                                                     :notes, 
                                                                                     :one_year_target_price, 
                                                                                     :open, 
                                                                                     :order_book, 
                                                                                     :pe_ratio, 
                                                                                     :pe_ratio_realtime, 
                                                                                     :peg_ratio, 
                                                                                     :percent_change_from_200_day_moving_average, 
                                                                                     :percent_change_from_50_day_moving_average, 
                                                                                     :percent_change_from_52_week_high, 
                                                                                     :percent_change_from_52_week_low, 
                                                                                     :previous_close, 
                                                                                     :price_eps_estimate_current_year, 
                                                                                     :price_eps_Estimate_next_year, 
                                                                                     :price_paid, 
                                                                                     :price_per_book, 
                                                                                     :price_per_sales, 
                                                                                     :shares_owned, 
                                                                                     :short_ratio, 
                                                                                     :stock_exchange, 
                                                                                     :symbol, 
                                                                                     :ticker_trend, 
                                                                                     :trade_date,
                                                                                     :trade_links, 
                                                                                     :volume,
                                                                                     :weeks_range_52 ], { raw: false } )
  end

  def admin
  end
end

app/helpers/spinoffs_helper.rb
module SpinoffsHelper
end

app/views/spinoffs/_spinoffs.html.erb
<div class="container">
  <%= will_paginate @spinoffs, renderer: BootstrapPagination::Rails %>
</div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th><h3>Parent Name</h3></th>
        <th><h3>Parent Ticker</h3></th>
        <th><h3>Spinoff Name</h3></th>
        <th><h3>Spinoff Ticker</h3></th>
        <th><h3>Spinoff Date</h3></th>
      </tr>
    </thead>
    <tbody>
      <% @spinoffs.each do |spin| %>
        <tr>
          <td><%= spin.parent_name %></td>
          <td><%= link_to spin.parent_ticker, controller: 'spinoffs', action: 'show', id: spin %></td>   
          <td><%= spin.spinoff_name %></td>
          <td><%= link_to spin.spinoff_ticker, controller: 'spinoffs', action: 'show', id: spin  %></td>
          <td><%= spin.spinoff_date %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<div class="container">
  <%= will_paginate @spinoffs, renderer: BootstrapPagination::Rails %>
</div>

app/views/spinoffs/index.html.erb
<% if current_user.subscribed %>
<header>
  <section class="hero">
    <div class="texture-overlay"></div>
    <div class="container">
      <%= render partial: "elements/navbar" %>
      <%= bootstrap_flash %>
      <div class="row hero-content">
        <div class="col-md-12">
          <h1 class="animated fadeInDown">Welcome Back To The Spinoff Newsletter</h1>
        </div>
      </div>
    </div>
  </section>
</header>

<div id="spinoffs" class="bg_dark">
    <%= render 'spinoffs' %>
</div>
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <p>© Spinoff Newsletter - Designed &amp; Developed by<br> <a href="http://www.ajeanwebdev.com/">Ajean Web Dev</a> &amp; <a href="https://github.com/palmbeachjeff">Palm Beach Jeff</a></p>
          </div>
        </div>
      </div>
    </footer>

<% else %>
<header>
      <section class="hero">
        <div class="texture-overlay"></div>
        <div class="container">
          <%= render partial: "elements/navbar" %>
          <%= bootstrap_flash %>
          <div class="row hero-content">
            <div class="col-md-12">
              <h1 class="animated fadeInDown">We provide a newsletter of recent and upcoming spinoffs for valued investors of all kinds</h1>
              <%= button_to "Subscribe", new_subscribe_path, :class => "use-btn animated fadeInUp", :method => :get  %> 
            </div>
          </div>
        </div>
      </section>
    </header>
    <section class="content_one">
      <div class='row'>
        <div class='col-md-6'>
          <h1 class="text_one">Definition of Spinoff</h1>
          <p class="faq" style="margin: 3% 0 0 5%;">The creation of an independent company through the sale or distribution of new shares of an existing business or division of a parent company. A spinoff is a type of divestiture. Businesses wishing to streamline their operations often sell less productive or unrelated subsidiary businesses as spinoffs. For example, a company might spin off one of its mature business units that is experiencing little or no growth so it can focus on a product or service with higher growth prospects. The spun-off companies are expected to be worth more as independent entities than as parts of a larger business.</p>
        </div>
        <div class='col-md-6'>
          <%= image_tag('Stock_Market_background.jpg', class: 'img_one') %>
        </div>
      </div>
    </section>
    
    <section class="showcase">
      <div class="showcase-wrap">
        <div class="texture-overlay"></div>
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <div class="device wp3">
                <div class="device-content">
                  <div class="showcase-slider">
                    <ul class="slides" id="showcaseSlider">
                      <li>
                        
                      </li>
                      <li>
                        
                      </li>
                      <li>
                        
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-6">
              <h1 class="text_one">Have a question?</h1>
              <p class="faq">Spinoffs often leave many investors scratching their heads and wondering what exactly this new company does. Thankfully, SEC Form 10-12B usually contains a substantial information letter or "narrative" that outlines the reason for the spin-off, the potential strengths and weaknesses of the new company and the outlooks for new companies industry. </p>
                <p class="faq">SEC Form 10-12B contains information about the original shares issued, the new shares affected and information about how and on which exchange the new shares will trade.</p>
              <%= link_to "FAQ", faq_show_path, class: "download-btn", :method => :get %>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="screenshots-intro">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <h1 class="text_two">Let us keep you up to date</h1>
            <p class="text_two">Spinoffs are a common occurrence; there are typically about 50 per year in the United States. You may be familiar with Expedia’s spinoff of TripAdvisor in 2011, United Online’s spinoff of FTD companies in 2013 or Sears Holding Corporation’s spinoff of Sears Canada in 2012, to name just a few examples.</p>
            <p class="text_two">A corporation creates a spinoff by distributing 100% of its ownership interest in that business unit as a stock dividend to existing shareholders. It can also offer its existing shareholders a discount to exchange their shares in the parent for shares of the spinoff. For example, an investor could exchange $100 of the parent’s stock for $110 of the spinoff’s stock. Spinoffs tend to increase returns for shareholders because the newly independent companies can better focus on their specific products or services. Both the parent and the spinoff tend to perform better as a result of the spinoff transaction, with the spinoff being the greater performer.</p>
          </div>
        </div>
      </div>
    </section>
    
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <p>© Spinoff Newsletter - Designed &amp; Developed by<br> <a href="http://www.ajeanwebdev.com/">Ajean Web Dev</a> &amp; <a href="https://github.com/palmbeachjeff">Palm Beach Jeff</a></p>
          </div>
        </div>
      </div>
    </footer>
<% end %>

app/views/spinoffs/index.js.erb
$("#spinoffs").html("<%= j(render('spinoffs')) %>");

app/views/spinoffs/show.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "The Spinoff Newsletter", defined?(root_path) ? root_path : "#", class: "navbar-brand logo" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="navbar-collapse-1">
    <ul class="nav navbar-nav">
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if defined?(Devise) %>
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Account", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path, class: 'nav_links' %></li>
          <li><%= link_to "Sign Up", new_user_registration_path, class: 'nav_links' %></li>
        <% end %>
      <% end %>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>
<div class="container">
  <h1 style="padding-top: 2.3em; padding-bottom: 0.4em; font-size: 3.4em;"><%= @spinoff.parent_name %></h1>
</div>
<div class="bg_dark">
<div class="row">
  <div class="col-md-8">
    <div id="container_parent" style="width:100%; height:400px;"></div>
  </div>
  <div class="col-md-4">
    <table class="table table-striped">
      <thead>
        <tr>
          <th><h2>Change</h2></th>
          <th><h2>Change In Percent</h2></th>
          <th><h2>Close</h2></th>
          <th><h2>Last Trade Price</h2></th>
        </tr>
      </thead>
      <tbody>
          <tr>
            <td><%= @data[0].change %></td>  
            <td><%= @data[0].change_in_percent %></td>
            <td><%= @data[0].close %></td>
            <td><%= @data[0].last_trade_price %></td>
          </tr>
      </tbody>
      <thead>
        <tr>
          <th><h2>Bid</h2></th>
          <th><h2>Ask</h2></th>
          <th><h2>Last Trade Time</h2></th>
          <th><h2>Last Trade Date</h2></th>
        </tr>
      </thead>
      <tbody>
          <td><%= @data[0].bid %></td>
          <td><%= @data[0].ask %></td>
          <td><%= @data[0].last_trade_time %></td>
          <td><%= @data[0].last_trade_date %></td>
      </tbody>
      <thead>
        <tr>
          <th><h2>Price Per Sales</h2></th>
          <th><h2>Earnings Per Share</h2></th>
          <th><h2>Open</h2></th>
          <th><h2>Stock Exchange</h2></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @data[0].price_per_sales %></td>  
          <td><%= @data[0].earnings_per_share %></td>
          <td><%= @data[0].open %></td>
          <td><%= @data[0].stock_exchange %></td>
        </tr>
      </tbody>
        <thead>
          <tr>
            <th><h2>Bid Size</h2></th>
            <th><h2>Ask Size</h2></th>
            <th><h2>Average Daily Volume</h2></th>
            <th><h2>Dividend Pay Date</h2></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @data[0].bid_size %></td>
            <td><%= @data[0].ask_size %></td>
            <td><%= @data[0].average_daily_volume %></td>
            <td><%= @data[0].dividend_pay_date %></td>
          </tr>
        </tbody>
    </table>    
  </div>
</div>

</div>
<div class="container">
  <h1 style="padding-top: 2.3em; padding-bottom: 0.4em; font-size: 3.4em;"><%= @spinoff.spinoff_name %></h1>
</div>
<div class="bg_dark">
<div class="row">
  <div class="col-md-8">
    <div id="container_spinoff" style="width:100%; height:400px;"></div>
  </div>
  <div class="col-md-4">
    <table class="table table-striped">
      <thead>
        <tr>
          <th><h2>Change</h2></th>
          <th><h2>Change In Percent</h2></th>
          <th><h2>Close</h2></th>
          <th><h2>Last Trade Price</h2></th>
        </tr>
      </thead>
      <tbody>
          <tr>
            <td><%= @data[1].change %></td>  
            <td><%= @data[1].change_in_percent %></td>
            <td><%= @data[1].close %></td>
            <td><%= @data[1].last_trade_price %></td>
          </tr>
      </tbody>
      <thead>
        <tr>
          <th><h2>Bid</h2></th>
          <th><h2>Ask</h2></th>
          <th><h2>Last Trade Time</h2></th>
          <th><h2>Last Trade Date</h2></th>
        </tr>
      </thead>
      <tbody>
          <td><%= @data[1].bid %></td>
          <td><%= @data[1].ask %></td>
          <td><%= @data[1].last_trade_time %></td>
          <td><%= @data[1].last_trade_date %></td>
      </tbody>
      <thead>
        <tr>
          <th><h2>Price Per Sales</h2></th>
          <th><h2>Earnings Per Share</h2></th>
          <th><h2>Open</h2></th>
          <th><h2>Stock Exchange</h2></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @data[1].price_per_sales %></td>  
          <td><%= @data[1].earnings_per_share %></td>
          <td><%= @data[1].open %></td>
          <td><%= @data[1].stock_exchange %></td>
        </tr>
      </tbody>
        <thead>
          <tr>
            <th><h2>Bid Size</h2></th>
            <th><h2>Ask Size</h2></th>
            <th><h2>Average Daily Volume</h2></th>
            <th><h2>Dividend Pay Date</h2></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @data[1].bid_size %></td>
            <td><%= @data[1].ask_size %></td>
            <td><%= @data[1].average_daily_volume %></td>
            <td><%= @data[1].dividend_pay_date %></td>
          </tr>
        </tbody>
    </table>    
  </div>
</div>

</div>

    <footer>
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <p>© Spinoff Newsletter - Designed &amp; Developed by<br> <a href="http://www.ajeanwebdev.com/">Ajean Web Dev</a> &amp; <a href="https://github.com/palmbeachjeff">Palm Beach Jeff</a></p>
          </div>
        </div>
      </div>
    </footer>

<script>
$(function () {
    $('#container_parent').highcharts({
        chart: {
            zoomType: 'x'
        },
        title: {
            text: '<%= @spinoff.parent_ticker %>'
        },
        subtitle: {
            text: document.ontouchstart === undefined ?
                    'Click and drag in the plot area to zoom in' :
                    'Pinch the chart to zoom in'
        },
        xAxis: {
            type: 'datetime',
            minRange: 14 * 24 * 3600000 // fourteen days
        },
        yAxis: {
            title: {
                text: 'Price'
            }
        },
        legend: {
            enabled: false
        },
        plotOptions: {
            area: {
                fillColor: {
                    linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1},
                    stops: [
                        [0, Highcharts.getOptions().colors[1]],
                        [1, Highcharts.Color(Highcharts.getOptions().colors[4]).setOpacity(0).get('rgba')]
                    ]
                },
                marker: {
                    radius: 2
                },
                lineWidth: 1,
                states: {
                    hover: {
                        lineWidth: 1
                    }
                },
                threshold: null
            }
        },

        series: [{
            type: 'area',
            name: '<%= @spinoff.spinoff_ticker %>',
            pointInterval: 24 * 3600 * 1000,
            pointStart: Date.UTC(2010, 0, 1),
            data: <%= @data_history_p.collect { |c| c.close.to_f }.reverse %>
        }]
    });

$('#container_spinoff').highcharts({
        chart: {
            zoomType: 'x'
        },
        title: {
            text: '<%= @data[1].symbol %>'
        },
        subtitle: {
            text: document.ontouchstart === undefined ?
                    'Click and drag in the plot area to zoom in' :
                    'Pinch the chart to zoom in'
        },
        xAxis: {
            type: 'datetime',
            minRange: 14 * 24 * 3600000 // fourteen days
        },
        yAxis: {
            title: {
                text: 'Price'
            }
        },
        legend: {
            enabled: false
        },
        plotOptions: {
            area: {
                fillColor: {
                    linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1},
                    stops: [
                        [0, Highcharts.getOptions().colors[2]],
                        [1, Highcharts.Color(Highcharts.getOptions().colors[1]).setOpacity(0).get('rgba')]
                    ]
                },
                marker: {
                    radius: 2
                },
                lineWidth: 1,
                states: {
                    hover: {
                        lineWidth: 1
                    }
                },
                threshold: null
            }
        },

        series: [{
            type: 'area',
            name: '<%= @data[1].symbol %>',
            pointInterval: 24 * 3600 * 1000,
            pointStart: Date.UTC(2010, 0, 1),
            data: <%= @data_history_s.collect { |c| c.close.to_f }.reverse %>
        }]
    });
});
</script>

app/views/spinoffs/show.js.erb
 $(function () {
    $('#container').highcharts('StockChart', {

        legend: {
            enabled: true,
            align: 'right',
            backgroundColor: '#FCFFC5',
            borderColor: 'black',
            borderWidth: 2,
            layout: 'vertical',
            verticalAlign: 'top',
            y: 100,
            shadow: true
        },

        rangeSelector: {
            selected: 1
        },

        series: [{
            name: "<%= @spinoff.parent_ticker %>",
            data: ADBE
        }, {
            name: "<%= @spinoff.spinoff_ticker %>",
            data: MSFT
        }]
    });
});  